// ============================================================
//  lib/models/business_card.dart
//  Model Class — QR Business Card Module
// ============================================================
//
//  WHAT IS A MODEL CLASS?
//  ─────────────────────────────────────────────────────────
//  A model class (also called a Data Class) is a plain Dart
//  class whose only job is to hold data. It has:
//
//  1. ATTRIBUTES  — the fields / properties the object holds
//  2. CONSTRUCTOR — how you create an instance of the class
//  3. fromJson()  — converts a raw Map (from Supabase/API)
//                   into a typed Dart object
//  4. toJson()    — converts this Dart object back into a Map
//                   so Supabase can store it
//  5. copyWith()  — creates a NEW object with some fields
//                   changed (used during edit/update)
//  6. toString()  — returns a readable string for debugging
//
//  SUPABASE TABLE: business_cards
//  ┌──────────────┬──────────────────┬──────────────────────┐
//  │ Column        │ Dart Field       │ Dart Type            │
//  ├──────────────┼──────────────────┼──────────────────────┤
//  │ id            │ id               │ String               │
//  │ user_id       │ userId           │ String               │
//  │ name          │ name             │ String               │
//  │ email         │ email            │ String? (nullable)   │
//  │ phone         │ phone            │ String? (nullable)   │
//  │ company       │ company          │ String? (nullable)   │
//  │ job_title     │ jobTitle         │ String? (nullable)   │
//  │ website       │ website          │ String? (nullable)   │
//  │ created_at    │ createdAt        │ DateTime             │
//  │ updated_at    │ updatedAt        │ DateTime             │
//  └──────────────┴──────────────────┴──────────────────────┘
//
// ============================================================

class BusinessCard {
  // ── 1. ATTRIBUTES ─────────────────────────────────────────
  //
  //  All fields are marked 'final' which means they CANNOT be
  //  changed after the object is created. This is called
  //  immutability — a best practice in Flutter/Dart.
  //
  //  Fields ending with ? are NULLABLE — they can hold either
  //  a String value or null (meaning "not provided").
  //  Fields without ? are REQUIRED — they must always have a value.

  final String id;           // UUID generated by Supabase — e.g. "a1b2c3d4-..."
  final String userId;       // The auth.users.id of the owner
  final String name;         // Full name — the only required user field
  final String? email;       // Optional: contact email address
  final String? phone;       // Optional: phone number
  final String? company;     // Optional: employer / organization
  final String? jobTitle;    // Optional: position / role
  final String? website;     // Optional: personal or company URL
  final DateTime createdAt;  // Timestamp — auto-set by Supabase on INSERT
  final DateTime updatedAt;  // Timestamp — auto-updated by Supabase trigger

  // ── 2. CONSTRUCTOR ────────────────────────────────────────
  //
  //  Named parameters (inside curly braces {}) are used so that
  //  you must name each argument when creating an object:
  //
  //    BusinessCard(name: 'Ali', id: 'xyz', ...)
  //
  //  'required' means the caller MUST provide that argument.
  //  Fields without 'required' (like email, phone) are optional
  //  and default to null if not provided.

  const BusinessCard({
    required this.id,
    required this.userId,
    required this.name,
    this.email,           // Optional → defaults to null
    this.phone,           // Optional → defaults to null
    this.company,         // Optional → defaults to null
    this.jobTitle,        // Optional → defaults to null
    this.website,         // Optional → defaults to null
    required this.createdAt,
    required this.updatedAt,
  });

  // ── 3. fromJson() ─────────────────────────────────────────
  //
  //  A FACTORY CONSTRUCTOR that builds a BusinessCard from a
  //  Map<String, dynamic>. This is the data format Supabase
  //  returns when you query a table row.
  //
  //  Example Map from Supabase:
  //  {
  //    'id': 'a1b2-...',
  //    'user_id': 'u9x8-...',
  //    'name': 'Ali Khan',
  //    'email': 'ali@example.com',
  //    'phone': null,
  //    'company': 'FAST University',
  //    'job_title': null,
  //    'website': null,
  //    'created_at': '2025-01-15T10:30:00.000Z',
  //    'updated_at': '2025-01-15T10:30:00.000Z'
  //  }
  //
  //  'as String'  → casts the dynamic value to String (required)
  //  'as String?' → casts to nullable String (optional fields)
  //  DateTime.parse() → converts ISO 8601 string into DateTime

  factory BusinessCard.fromJson(Map<String, dynamic> json) {
    return BusinessCard(
      id:        json['id']        as String,
      userId:    json['user_id']   as String,
      name:      json['name']      as String,
      email:     json['email']     as String?,
      phone:     json['phone']     as String?,
      company:   json['company']   as String?,
      jobTitle:  json['job_title'] as String?,
      website:   json['website']   as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
    );
  }

  // ── 4. toJson() ───────────────────────────────────────────
  //
  //  Converts this object into a Map<String, dynamic> so it
  //  can be sent to Supabase in INSERT or UPDATE operations.
  //
  //  NOTE: We deliberately EXCLUDE:
  //  • id        → Supabase auto-generates a UUID
  //  • user_id   → Supabase fills this from auth.uid() via RLS
  //  • created_at / updated_at → auto-managed by Supabase
  //
  //  The Map keys MUST match the exact column names in Supabase.

  Map<String, dynamic> toJson() {
    return {
      'name':      name,
      'email':     email,
      'phone':     phone,
      'company':   company,
      'job_title': jobTitle,
      'website':   website,
    };
  }

  // ── 5. copyWith() ─────────────────────────────────────────
  //
  //  Returns a NEW BusinessCard with some fields replaced.
  //  The original object is NOT modified (immutability).
  //
  //  HOW IT WORKS:
  //  Each parameter is nullable (String? id). If the caller
  //  passes a value, use it. If they pass null, keep the
  //  existing value using the ?? (null-coalescing) operator.
  //
  //  USAGE EXAMPLE:
  //    final updated = card.copyWith(name: 'New Name');
  //    // updated.name == 'New Name'
  //    // updated.email == card.email  (unchanged)

  BusinessCard copyWith({
    String?   id,
    String?   userId,
    String?   name,
    String?   email,
    String?   phone,
    String?   company,
    String?   jobTitle,
    String?   website,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return BusinessCard(
      id:        id        ?? this.id,
      userId:    userId    ?? this.userId,
      name:      name      ?? this.name,
      email:     email     ?? this.email,
      phone:     phone     ?? this.phone,
      company:   company   ?? this.company,
      jobTitle:  jobTitle  ?? this.jobTitle,
      website:   website   ?? this.website,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  // ── 6. toString() ─────────────────────────────────────────
  //
  //  Override the default toString() for readable debug output.
  //  When you print(card), you see this string instead of
  //  "Instance of 'BusinessCard'".

  @override
  String toString() {
    return 'BusinessCard('
        'id: $id, '
        'name: $name, '
        'company: ${company ?? "N/A"}, '
        'email: ${email ?? "N/A"}'
        ')';
  }
}
