// ============================================================
//  lib/models/recording.dart
//  Model Class — Audio Recorder Module
// ============================================================
//
//  Represents ONE saved audio recording. The model stores
//  METADATA only — the actual audio file lives in
//  Supabase Storage and is referenced by filePath.
//
//  SUPABASE TABLE: recordings
//  ┌──────────────┬──────────────────┬──────────────────────┐
//  │ Column        │ Dart Field       │ Dart Type            │
//  ├──────────────┼──────────────────┼──────────────────────┤
//  │ id            │ id               │ String               │
//  │ user_id       │ userId           │ String               │
//  │ title         │ title            │ String               │
//  │ notes         │ notes            │ String               │
//  │ file_path     │ filePath         │ String               │
//  │ duration_ms   │ durationMs       │ int                  │
//  │ created_at    │ createdAt        │ DateTime             │
//  └──────────────┴──────────────────┴──────────────────────┘
//
//  SUPABASE STORAGE:
//  Audio files are stored in the 'recordings' bucket at path:
//    {userId}/{uuid}.m4a
//  The filePath field stores exactly this storage path.
//
// ============================================================

class Recording {
  // ── 1. ATTRIBUTES ─────────────────────────────────────────

  final String id;          // UUID — auto-generated by Supabase
  final String userId;      // Owner of this recording
  final String title;       // User-provided recording name
  final String notes;       // Optional text notes (empty string if none)
  final String filePath;    // Supabase Storage path: "{userId}/{file}.m4a"
  final int durationMs;     // Length of audio in milliseconds
                            //   e.g. 65000 = 1 minute 5 seconds
  final DateTime createdAt; // When the recording was saved

  // ── 2. CONSTRUCTOR ────────────────────────────────────────
  //
  //  'notes' and 'durationMs' are required in the constructor
  //  but have safe defaults in fromJson() ('' and 0) to handle
  //  older records that might not have these values.

  const Recording({
    required this.id,
    required this.userId,
    required this.title,
    required this.notes,
    required this.filePath,
    required this.durationMs,
    required this.createdAt,
  });

  // ── 3. fromJson() ─────────────────────────────────────────
  //
  //  Converts a Supabase row Map into a Recording object.
  //
  //  Example Map from Supabase:
  //  {
  //    'id': 'r5s6t7-...',
  //    'user_id': 'u9x8-...',
  //    'title': 'Lecture Notes - OOP',
  //    'notes': 'Chapter 3 summary',
  //    'file_path': 'u9x8.../abc123.m4a',
  //    'duration_ms': 125000,
  //    'created_at': '2025-04-01T09:00:00.000Z'
  //  }
  //
  //  The ?? operator provides a DEFAULT VALUE when the field
  //  is null in the database:
  //    json['notes'] as String? ?? ''  →  use '' if notes is null
  //    json['duration_ms'] as int? ?? 0 → use 0 if duration is null

  factory Recording.fromJson(Map<String, dynamic> json) {
    return Recording(
      id:         json['id']          as String,
      userId:     json['user_id']     as String,
      title:      json['title']       as String,
      notes:      json['notes']       as String? ?? '',
      filePath:   json['file_path']   as String,
      durationMs: json['duration_ms'] as int?    ?? 0,
      createdAt:  DateTime.parse(json['created_at'] as String),
    );
  }

  // ── 4. toJson() ───────────────────────────────────────────
  //
  //  Used when INSERTING a new recording into Supabase.
  //  Excludes: id, user_id (server-managed), created_at.

  Map<String, dynamic> toJson() {
    return {
      'title':       title,
      'notes':       notes,
      'file_path':   filePath,
      'duration_ms': durationMs,
    };
  }

  // ── 5. copyWith() ─────────────────────────────────────────
  //
  //  Used when editing a recording's title or notes.
  //  The audio file itself never changes — only metadata.
  //
  //  USAGE:
  //    final updated = recording.copyWith(title: 'New Title');

  Recording copyWith({
    String?   id,
    String?   userId,
    String?   title,
    String?   notes,
    String?   filePath,
    int?      durationMs,
    DateTime? createdAt,
  }) {
    return Recording(
      id:         id         ?? this.id,
      userId:     userId     ?? this.userId,
      title:      title      ?? this.title,
      notes:      notes      ?? this.notes,
      filePath:   filePath   ?? this.filePath,
      durationMs: durationMs ?? this.durationMs,
      createdAt:  createdAt  ?? this.createdAt,
    );
  }

  // ── 6. COMPUTED PROPERTY: formattedDuration ───────────────
  //
  //  A getter (not stored in DB) that converts the raw
  //  milliseconds value into a human-readable "mm:ss" string.
  //
  //  HOW IT WORKS:
  //  ~/ is integer division (discards decimal part):
  //    125000 ms ÷ 1000 = 125 total seconds
  //    125 ÷ 60 = 2 minutes  (125 ~/ 60 = 2)
  //    125 % 60 = 5 seconds  (125 mod 60 = 5)
  //    Result: "2:05"
  //
  //  padLeft(2, '0') adds a leading zero:
  //    "5" → "05",  "15" → "15"

  String get formattedDuration {
    final totalSeconds = durationMs ~/ 1000;
    final minutes      = totalSeconds ~/ 60;
    final seconds      = totalSeconds % 60;
    return '$minutes:${seconds.toString().padLeft(2, '0')}';
  }

  // ── 7. toString() ─────────────────────────────────────────

  @override
  String toString() {
    return 'Recording('
        'id: $id, '
        'title: $title, '
        'duration: $formattedDuration, '
        'filePath: $filePath'
        ')';
  }
}
