// ============================================================
//  lib/models/scan_history.dart
//  Model Class — QR Scan History Module
// ============================================================
//
//  Every time the user scans a QR code with the camera,
//  the decoded text is saved as a ScanHistory record.
//  This model represents ONE scanned entry.
//
//  SUPABASE TABLE: scan_history
//  ┌──────────────┬──────────────────┬──────────────────────┐
//  │ Column        │ Dart Field       │ Dart Type            │
//  ├──────────────┼──────────────────┼──────────────────────┤
//  │ id            │ id               │ String               │
//  │ user_id       │ userId           │ String               │
//  │ scanned_text  │ scannedText      │ String               │
//  │ scanned_at    │ scannedAt        │ DateTime             │
//  └──────────────┴──────────────────┴──────────────────────┘
//
//  NOTE: ScanHistory does NOT have a copyWith() because
//  scan records are never edited — only created or deleted.
//
// ============================================================

class ScanHistory {
  // ── 1. ATTRIBUTES ─────────────────────────────────────────

  final String id;           // UUID — auto-generated by Supabase
  final String userId;       // Owner of this scan entry
  final String scannedText;  // The raw decoded QR content
                             //   e.g. "https://example.com"
                             //   e.g. "BEGIN:VCARD\nFN:Ali Khan..."
                             //   e.g. "Any plain text"
  final DateTime scannedAt;  // When the scan happened — auto-set

  // ── 2. CONSTRUCTOR ────────────────────────────────────────
  //
  //  All four fields are required — a scan entry is useless
  //  without any of them.

  const ScanHistory({
    required this.id,
    required this.userId,
    required this.scannedText,
    required this.scannedAt,
  });

  // ── 3. fromJson() ─────────────────────────────────────────
  //
  //  Converts the Supabase row Map into a ScanHistory object.
  //
  //  Example Map from Supabase:
  //  {
  //    'id': 'c3d4e5-...',
  //    'user_id': 'u9x8-...',
  //    'scanned_text': 'https://fast.edu.pk',
  //    'scanned_at': '2025-03-10T14:22:00.000Z'
  //  }

  factory ScanHistory.fromJson(Map<String, dynamic> json) {
    return ScanHistory(
      id:          json['id']           as String,
      userId:      json['user_id']      as String,
      scannedText: json['scanned_text'] as String,
      scannedAt:   DateTime.parse(json['scanned_at'] as String),
    );
  }

  // ── 4. toJson() ───────────────────────────────────────────
  //
  //  Used when INSERTING a new scan record into Supabase.
  //  Only scanned_text is needed — all other fields are
  //  either auto-generated (id) or set server-side (user_id,
  //  scanned_at via DEFAULT NOW()).

  Map<String, dynamic> toJson() {
    return {
      'scanned_text': scannedText,
    };
  }

  // ── 5. toString() ─────────────────────────────────────────

  @override
  String toString() {
    return 'ScanHistory('
        'id: $id, '
        'scannedText: $scannedText, '
        'scannedAt: $scannedAt'
        ')';
  }
}
